import React, { useState, useEffect } from 'react';
import { Bell, AlertTriangle, ShieldCheck, UserPlus, Loader2, Check } from 'lucide-react';

const ParentNotifications = () => {
  const [loading, setLoading] = useState(true);
  const [notifications, setNotifications] = useState([]);
  const [currentPage, setCurrentPage] = useState(1);
  const itemsPerPage = 5;

  useEffect(() => {
    const fetchNotifications = async () => {
      setLoading(true);
      try {
        await new Promise(resolve => setTimeout(resolve, 1000));

        setNotifications([
          { id: 1, type: 'alert', title: 'HIGH SEVERITY ALERT', message: 'Unusual activity detected in Care Circle #44.', time: '10:42 AM', date: 'Today', read: false },
          { id: 2, type: 'system', title: 'SYSTEM UPDATE', message: 'Monthly security patch applied successfully.', time: '08:15 AM', date: 'Today', read: false },
          { id: 3, type: 'user', title: 'NEW USER REGISTRATION', message: 'Julianna Abrams joined as Parent.', time: '03:22 PM', date: 'Yesterday', read: true },
          { id: 4, type: 'report', title: 'REPORT GENERATED', message: 'System Overview Report generated by Admin.', time: '11:05 AM', date: 'Yesterday', read: true },
          { id: 5, type: 'alert', title: 'MEDIUM SEVERITY ALERT', message: 'Failed login attempt from unrecognized IP.', time: '09:30 AM', date: 'Oct 24', read: true },
          { id: 6, type: 'system', title: 'BACKUP COMPLETE', message: 'Weekly data backup completed with zero errors.', time: '02:00 AM', date: 'Oct 24', read: true },
          { id: 7, type: 'user', title: 'ROLE UPDATE', message: 'Marcus Thorne role changed to Provider.', time: '04:15 PM', date: 'Oct 23', read: true },
        ]);
      } finally {
        setLoading(false);
      }
    };
    fetchNotifications();
  }, []);

  const markAllAsRead = () => {
    setNotifications(prev => prev.map(n => ({ ...n, read: true })));
  };

  const markAsRead = (id) => {
    setNotifications(prev => prev.map(n => n.id === id ? { ...n, read: true } : n));
  };

  if (loading) {
    return (
      <div className="min-h-screen bg-white flex items-center justify-center">
        <div className="flex flex-col items-center gap-4 text-gray-400">
          <Loader2 className="animate-spin" size={32} />
          <p className="text-[10px] font-bold tracking-widest uppercase">Loading Notifications...</p>
        </div>
      </div>
    );
  }

  const totalPages = Math.ceil(notifications.length / itemsPerPage) || 1;
  const startIndex = (currentPage - 1) * itemsPerPage;
  const currentItems = notifications.slice(startIndex, startIndex + itemsPerPage);

  const unreadCount = notifications.filter(n => !n.read).length;

  const getIcon = (type) => {
    switch (type) {
      case 'alert': return <AlertTriangle size={18} className="text-red-500" />;
      case 'system': return <ShieldCheck size={18} className="text-gray-800" />;
      case 'user': return <UserPlus size={18} className="text-gray-600" />;
      default: return <Bell size={18} className="text-gray-600" />;
    }
  };

  return (
    <div className="min-h-screen p-8 bg-[#f8fafc] font-sans text-[#1e293b]">
      <div className="mx-auto max-w-5xl animate-in fade-in zoom-in duration-500">

        {/* Header */}
        <div className="flex flex-col md:flex-row justify-between items-start md:items-end gap-6 mb-10 border-b border-[#e2e8f0] pb-8">
          <div>
            <p className="text-[10px] font-bold text-[#64748b] tracking-[0.2em] uppercase mb-2">SYSTEM ALERTS</p>
            <h1 className="text-2xl sm:text-4xl font-black tracking-tighter uppercase flex items-center gap-4 text-[#1e293b]">
              Notifications
              {unreadCount > 0 && (
                <span className="bg-[#06b6d4] text-white text-[12px] sm:text-[14px] font-bold px-3 py-1 tracking-widest align-middle rounded-full">
                  {unreadCount} NEW
                </span>
              )}
            </h1>
          </div>
          <button
            onClick={markAllAsRead}
            disabled={unreadCount === 0}
            className="w-full md:w-auto bg-white border border-[#e2e8f0] hover:bg-[#f1f5f9] text-[#1e293b] text-[10px] font-bold tracking-wider uppercase px-6 py-3 rounded-lg shadow-sm transition-colors disabled:opacity-50"
          >
            MARK ALL AS READ
          </button>
        </div>

        {/* Notifications List */}
        <div className="flex flex-col min-h-[500px] bg-white rounded-xl shadow-sm border border-gray-100 overflow-hidden">
          {currentItems.map((notification) => (
            <div
              key={notification.id}
              className={`p-4 sm:p-6 flex items-start gap-4 sm:gap-6 border-b border-gray-100 transition-colors group relative last:border-0 ${notification.read ? 'bg-white hover:bg-[#f1f5f9]' : 'bg-[#f0fdfa] border-l-4 border-l-[#06b6d4] hover:bg-[#e0f2fe]'}`}
            >
              <div className="mt-1 bg-white p-2 shadow-sm rounded-lg border border-gray-100 shrink-0">
                {getIcon(notification.type)}
              </div>
              <div className="flex-1 min-w-0">
                <div className="flex flex-col sm:flex-row sm:justify-between sm:items-start mb-1 pr-8 lg:pr-0">
                  <h3 className={`text-[12px] tracking-widest uppercase mb-1 sm:mb-0 ${notification.read ? 'text-[#64748b] font-bold' : 'text-[#1e293b] font-black'}`}>
                    {notification.title}
                  </h3>
                  <span className="text-[9px] sm:text-[10px] text-[#94a3b8] font-bold tracking-widest uppercase shrink-0">
                    {notification.date} &bull; {notification.time}
                  </span>
                </div>
                <p className={`text-[13px] sm:text-[14px] leading-relaxed mt-1 ${notification.read ? 'text-[#64748b]' : 'text-[#334155]'}`}>
                  {notification.message}
                </p>
              </div>
              {!notification.read && (
                <button
                  onClick={() => markAsRead(notification.id)}
                  className="absolute right-4 top-4 lg:relative lg:right-auto lg:top-auto opacity-100 lg:opacity-0 lg:group-hover:opacity-100 transition-opacity p-2 text-[#94a3b8] hover:text-[#06b6d4] hover:bg-[#e0f2fe] rounded-lg"
                  title="Mark as read"
                >
                  <Check size={16} strokeWidth={3} />
                </button>
              )}
            </div>
          ))}
        </div>

        {/* Pagination */}
        <div className="bg-white rounded-xl shadow-sm border border-gray-100 px-4 md:px-6 py-4 flex flex-col md:flex-row gap-4 justify-between items-center mt-6">
          <span className="text-[9px] font-bold text-[#64748b] tracking-widest uppercase text-center md:text-left">
            SHOWING {notifications.length > 0 ? startIndex + 1 : 0}-{Math.min(startIndex + itemsPerPage, notifications.length)} OF {notifications.length} EVENTS
          </span>
          <div className="flex flex-wrap justify-center gap-1.5">
            <button
              onClick={() => setCurrentPage(prev => Math.max(prev - 1, 1))}
              disabled={currentPage === 1}
              className="w-8 h-8 rounded-lg flex items-center justify-center bg-white text-[#64748b] hover:bg-[#f1f5f9] transition-colors text-[10px] font-bold disabled:opacity-50 disabled:cursor-not-allowed border border-[#e2e8f0] shrink-0"
            >
              &lt;
            </button>

            {Array.from({ length: totalPages }, (_, i) => i + 1).map((page) => (
              <button
                key={page}
                onClick={() => setCurrentPage(page)}
                className={`w-8 h-8 rounded-lg flex items-center justify-center transition-colors text-[10px] font-bold border shrink-0 ${currentPage === page
                  ? 'bg-[#06b6d4] text-white border-[#06b6d4] shadow-sm'
                  : 'bg-white text-[#64748b] hover:bg-[#f1f5f9] border-[#e2e8f0]'
                  }`}
              >
                {page}
              </button>
            ))}

            <button
              onClick={() => setCurrentPage(prev => Math.min(prev + 1, totalPages))}
              disabled={currentPage === totalPages || totalPages === 0}
              className="w-8 h-8 rounded-lg flex items-center justify-center bg-white text-[#64748b] hover:bg-[#f1f5f9] transition-colors text-[10px] font-bold disabled:opacity-50 disabled:cursor-not-allowed border border-[#e2e8f0] shrink-0"
            >
              &gt;
            </button>
          </div>
        </div>

      </div>
    </div>
  );
};

export default ParentNotifications;
