import React, { useState, useEffect } from 'react';
import { Bell, AlertTriangle, ShieldCheck, UserPlus, Loader2, Check } from 'lucide-react';

const ParentNotifications = () => {
  const [loading, setLoading] = useState(true);
  const [notifications, setNotifications] = useState([]);
  const [currentPage, setCurrentPage] = useState(1);
  const itemsPerPage = 5;

  useEffect(() => {
    const fetchNotifications = async () => {
      setLoading(true);
      try {
        await new Promise(resolve => setTimeout(resolve, 1000));
        
        setNotifications([
          { id: 1, type: 'alert', title: 'HIGH SEVERITY ALERT', message: 'Unusual activity detected in Care Circle #44.', time: '10:42 AM', date: 'Today', read: false },
          { id: 2, type: 'system', title: 'SYSTEM UPDATE', message: 'Monthly security patch applied successfully.', time: '08:15 AM', date: 'Today', read: false },
          { id: 3, type: 'user', title: 'NEW USER REGISTRATION', message: 'Julianna Abrams joined as Parent.', time: '03:22 PM', date: 'Yesterday', read: true },
          { id: 4, type: 'report', title: 'REPORT GENERATED', message: 'System Overview Report generated by Admin.', time: '11:05 AM', date: 'Yesterday', read: true },
          { id: 5, type: 'alert', title: 'MEDIUM SEVERITY ALERT', message: 'Failed login attempt from unrecognized IP.', time: '09:30 AM', date: 'Oct 24', read: true },
          { id: 6, type: 'system', title: 'BACKUP COMPLETE', message: 'Weekly data backup completed with zero errors.', time: '02:00 AM', date: 'Oct 24', read: true },
          { id: 7, type: 'user', title: 'ROLE UPDATE', message: 'Marcus Thorne role changed to Provider.', time: '04:15 PM', date: 'Oct 23', read: true },
        ]);
      } finally {
        setLoading(false);
      }
    };
    fetchNotifications();
  }, []);

  const markAllAsRead = () => {
    setNotifications(prev => prev.map(n => ({ ...n, read: true })));
  };

  const markAsRead = (id) => {
    setNotifications(prev => prev.map(n => n.id === id ? { ...n, read: true } : n));
  };

  if (loading) {
    return (
      <div className="min-h-screen bg-white flex items-center justify-center">
        <div className="flex flex-col items-center gap-4 text-gray-400">
          <Loader2 className="animate-spin" size={32} />
          <p className="text-[10px] font-bold tracking-widest uppercase">Loading Notifications...</p>
        </div>
      </div>
    );
  }

  const totalPages = Math.ceil(notifications.length / itemsPerPage) || 1;
  const startIndex = (currentPage - 1) * itemsPerPage;
  const currentItems = notifications.slice(startIndex, startIndex + itemsPerPage);
  
  const unreadCount = notifications.filter(n => !n.read).length;

  const getIcon = (type) => {
    switch (type) {
      case 'alert': return <AlertTriangle size={18} className="text-red-500" />;
      case 'system': return <ShieldCheck size={18} className="text-gray-800" />;
      case 'user': return <UserPlus size={18} className="text-gray-600" />;
      default: return <Bell size={18} className="text-gray-600" />;
    }
  };

  return (
    <div className="min-h-screen p-8 bg-[#fdfdfd] font-sans text-[#111]">
      <div className="mx-auto max-w-5xl animate-in fade-in zoom-in duration-500">
        
        {/* Header */}
        <div className="flex justify-between items-end mb-10 border-b border-gray-200 pb-8">
          <div>
            <p className="text-[10px] font-bold text-gray-500 tracking-[0.2em] uppercase mb-2">SYSTEM ALERTS</p>
            <h1 className="text-5xl font-black tracking-tighter uppercase flex items-center gap-4">
              Notifications
              {unreadCount > 0 && (
                <span className="bg-black text-white text-[14px] font-bold px-3 py-1 tracking-widest align-middle">
                  {unreadCount} NEW
                </span>
              )}
            </h1>
          </div>
          <button 
            onClick={markAllAsRead}
            disabled={unreadCount === 0}
            className="bg-[#e8e8e8] hover:bg-gray-300 text-black text-[10px] font-bold tracking-wider uppercase px-6 py-3 transition-colors disabled:opacity-50"
          >
            MARK ALL AS READ
          </button>
        </div>

        {/* Notifications List */}
        <div className="flex flex-col min-h-[500px]">
          {currentItems.map((notification) => (
            <div 
              key={notification.id} 
              className={`p-6 flex items-start gap-6 border-b border-gray-100 transition-colors group ${notification.read ? 'bg-white hover:bg-gray-50' : 'bg-[#f4f4f4] border-l-4 border-black hover:bg-[#e8e8e8]'}`}
            >
              <div className="mt-1 bg-white p-2 shadow-sm border border-gray-100">
                {getIcon(notification.type)}
              </div>
              <div className="flex-1">
                <div className="flex justify-between items-start mb-1">
                  <h3 className={`text-[12px] tracking-widest uppercase ${notification.read ? 'text-gray-600 font-bold' : 'text-black font-black'}`}>
                    {notification.title}
                  </h3>
                  <span className="text-[10px] text-gray-400 font-bold tracking-widest uppercase">
                    {notification.date} &bull; {notification.time}
                  </span>
                </div>
                <p className={`text-[14px] leading-relaxed mt-1 ${notification.read ? 'text-gray-500' : 'text-gray-800'}`}>
                  {notification.message}
                </p>
              </div>
              {!notification.read && (
                <button 
                  onClick={() => markAsRead(notification.id)}
                  className="opacity-0 group-hover:opacity-100 transition-opacity p-2 text-gray-400 hover:text-black hover:bg-gray-200"
                  title="Mark as read"
                >
                  <Check size={16} strokeWidth={3} />
                </button>
              )}
            </div>
          ))}
        </div>

        {/* Pagination */}
        <div className="bg-[#f4f4f4] px-6 py-4 flex justify-between items-center mt-6">
          <span className="text-[9px] font-bold text-gray-500 tracking-widest uppercase">
            SHOWING {notifications.length > 0 ? startIndex + 1 : 0}-{Math.min(startIndex + itemsPerPage, notifications.length)} OF {notifications.length} EVENTS
          </span>
          <div className="flex gap-1.5">
            <button 
              onClick={() => setCurrentPage(prev => Math.max(prev - 1, 1))}
              disabled={currentPage === 1}
              className="w-8 h-8 flex items-center justify-center bg-white text-gray-500 hover:bg-gray-100 transition-colors text-[10px] font-bold disabled:opacity-50 disabled:cursor-not-allowed border border-[#e8e8e8]"
            >
              &lt;
            </button>
            
            {Array.from({ length: totalPages }, (_, i) => i + 1).map((page) => (
              <button
                key={page}
                onClick={() => setCurrentPage(page)}
                className={`w-8 h-8 flex items-center justify-center transition-colors text-[10px] font-bold border border-[#e8e8e8] ${
                  currentPage === page 
                    ? 'bg-black text-white border-black' 
                    : 'bg-white text-gray-500 hover:bg-gray-100'
                }`}
              >
                {page}
              </button>
            ))}

            <button 
              onClick={() => setCurrentPage(prev => Math.min(prev + 1, totalPages))}
              disabled={currentPage === totalPages || totalPages === 0}
              className="w-8 h-8 flex items-center justify-center bg-white text-gray-500 hover:bg-gray-100 transition-colors text-[10px] font-bold disabled:opacity-50 disabled:cursor-not-allowed border border-[#e8e8e8]"
            >
              &gt;
            </button>
          </div>
        </div>

      </div>
    </div>
  );
};

export default ParentNotifications;
